### ISSUE TITLE
Release v2.0.0 tag does not exist

### ISSUE THREAD

**Issue by ddka22** [edgeimpulse/mtb-example-edgeimpulse-keyword-spotting#2]
The release tag v2.0.0 was added to the edgeimpulse-ce-manifest-fv2.xml but the tag has not been created. Please create the release tag for the code example.

**Comment by faradayberry** [comment]
Sorry about that, after looking back at it I realized I hadn't pushed the tag to GH, but it should be fixed now:
brennandayberry@BrennanC0NBMD6V mtb-example-edgeimpulse-keyword-spotting % git push origin --tags
Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
To https://github.com/edgeimpulse/mtb-example-edgeimpulse-keyword-spotting.git
 * [new tag]         release-v2.0.0 -> release-v2.0.0
